language: java
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: yUVCtSxheQmQ3n/FlE1uSJQQCZQtE8DZpWURwDg8gQOyYdG04NNlsR/KTnozI58BPzPjVlZ0GkSXuDEdJELEWnpvp81Q3dWUsBirAcCbhpSEfWyHund63CAYvvdqJMnlOs4sQShizTJBUrqnGUT/pHU068YDlqvX+4pRZFGJHW65kg6odoRUjn2rQ7bf6PmjL3nAtLTNbnbfl5izgw315365XsX7Mx71cIX43FFPdVPbhollgYhIDJdmlUwCOb0IXAOV4WSv8Nw3WH5cekdKEtMNFrHT9COzHEcXbF6D9RYpJySOdJlL7ryBBJsMGQ7i75siA7SQiCjNCKsdXmpA2I1AsPSK9BHldn2fOokpkgV8nSaMxg/Sn8nh+VxOulpaj74FCjJ1bld6RTnE7CrA9QGQyX5Wi//C+OkwWr+y+Bj6WYBkgtF+MzACuxKuOsUFRQkPeHeTLDm0LGaouY5h3Hjco1Du32/zobdk2mNJX1KHbxc1gxxl9tPipitN4m7Zb4R1qXZbrwhmoETlfOQj3AH2sGgZiFMzECDi0K/cmaXrxXpWmAwi/ds48kLZGIvomBNgH1uXRpfzDBMogzTspENbXBDVriC3NcWgG+9eDAoYFrj2QFodl34rn5NYXWqeURBU1+haKJxCiucXD6d2nRJG6t1cFKkk5VnRuHgWGkU=
  app: TicTacToe
  on:
    repo: SevenSamurai2017/TicTacToe
