language: java
notifications:
  email: false
deploy:
  api_key:
    secure: hssZwvO28iuLiQnQnKJDjUtdDboO7PS0Y+giRS1ZaYraKVvUBzk0Q9MBP+teIV64ae82O0aoq8WEK6I80IiQ0gD3Ml/rbCtpBig6jGVYACXv5nDlDNJ7oVoXBTsrU0cc/PAXBDiDQZvyY3PgGZcmPU+1JrCwS6jj55bhP/rqdzshSDjta2S2kukdYUYvN83VOAKducE67zrawvChHiLeVpCVOirf+J4tTgIecH0VrZ2I0hrJymRRYcSYSNdMLvG2gEOrXSOcSf8DRuH8nH0w3kkEi0riKtIDruK6G8y6CCBfL9GGyvE2HuVOLzT9AC7WcLmJmT1H7TmTRm+CkylmAWY+KVL5ue8EkI8i2uSxFnq+sGDh3als5eUS4UnPvLP8cS9VQiA5fOTgbSbsCpL7+L1LyaRpHZfCZWtCEkip1HFCwt+uMpeEiPA6cDm41iHJd5RMRclW0/sys+D95scpgI/zE08ShML3/zEwubOYN7ElUlhEV9jl+EGGZCa71rNKUVc+pBFAemIrmR+vHGVnjdODIYkV1iseuiIVHFK70lTrUdgzXJi2wK8jBlfvCRyIjDYQRnkV7QWYFcRAINp1IgUWZquixSzCiDbr759KoXeChayKJmNiYsOGHr99eK4BslpKrfhec41JVhbQYZiDRzCudCzxurwzlzoTkcDoQpw=
